### ISSUE TITLE
[Bug] Aedes stops accepting subscribe/ publish

### ISSUE THREAD

**Issue by mogupta** [moscajs/aedes#483] opened 2020-05-07 00:08 UTC
Hello 

I have migrated from mosca few days back . I have a test server with ~10 clients connected and another production server with ~400 clients connected. The smaller instance works great but the bigger one stops responding to subscribe and publish requests after few days . Not sure what could be the cause. I checked the CPU/ memory usage. Its not high. 

**Aedes Code**
https://pastebin.com/raw/Zbf58pR1

**Logs  - I only see clients being connected but unable to publish / subscribe**
```
authorize :- device-5e3c5054ca15e200c69dd8c6
client connected Tin-fb49
authorize :- device-5e3c5054ca15e200c69dd8c6
client connected Tin-fb49
authorize :- device-5e3csdfsdfsdfsdfsdfsdfsdfsdf
client connected Tin-fb49
authorize :- device-5e3c5054ca15esdfsdfsdfsdfds
client connected Tin-rewr
```

**Comment by robertsLando** [comment] 2020-05-07 06:11
@mogupta Are you using all latest versions of aedes and persistences/mqemitters?

**Comment by mogupta** [comment] 2020-05-07 08:22
Hi @robertsLando 
I am using 
Aedes 0.41.0 
edes-persistence-mongodb 8.0.1 
mqemitter-mongodb 7.0.0 (This is old)

**Comment by robertsLando** [comment] 2020-05-07 09:05
@mogupta I have make some updates to mqemitter mongo so an update could fix things. After some tests the best choice for now is using redis as mqemitter and mongo as persistence and you shouldn't have any problem

**Comment by mogupta** [comment] 2020-05-07 09:06
thanks @robertsLando

**Comment by robertsLando** [comment] 2020-05-07 12:30
@mogupta I prefer to keep this open. PLease let me know if by updating mqemitter mongodb or by using redis you fix this then feel free to close the issue :)

**Comment by mogupta** [comment] 2020-05-07 23:01
@robertsLando same problem without any mq attached to aedes. With the default mqemitter too the same problem persists. Any suggestions where I can start digging ?

**Comment by robertsLando** [comment] 2020-05-08 06:10
@mogupta I dunno if the problem could be caused by authorize functions that are `async`. Could you please try to make them not async? simply replace await using promise.then.catch blocks.

I cannot notice anything else wrong, I see you are also using aedes stats that doesn't receive updates from a long time so I dunno if that could be a possible cause too. @gnought @mcollina do you have any idea?

**Comment by gnought** [comment] 2020-05-08 16:54
@mogupta What the result after disable authenticate, authorizePublish and authorizeSubscribe?

**Comment by mogupta** [comment] 2020-05-11 00:08
@gnought I removed authorizePublish, authorizeSubscribe, aedes stats , express monitor and removed bivac (docker volume backup) but the second day same problem surfaced. 

Just now I have upgrade the droplet to higher RAM/ CPU and have also removed authenticate hook. Will update you.

**Comment by robertsLando** [comment] 2020-05-11 09:26
Let us know. @mcollina Any ideas?

**Comment by mcollina** [comment] 2020-05-11 10:00
No idea and no time to investigatge :(

**Comment by mogupta** [comment] 2020-05-16 00:37
Hi guys, so upgrading the droplet to higher RAM/ CPU and removing the  authenticate hook fixed the problem. I will remove the async from authentication hook and see if it works.

**Comment by martin-doyle** [comment] 2020-05-16 09:09
Just an idea in order to reproduce the problem. I found https://github.com/inovex/mqtt-stresser more aggressive than https://github.com/krylovsk/mqtt-benchmark. I saw the same behaviour using this tool against Aedes running on a Raspberry Pi 3.

**Comment by robertsLando** [comment] 2020-05-16 09:39
Could you take a memory snapshot to see where the most memory is used by aedes? 

---

Daniel - Software Engineer

Support me at:
    Github sponsors

**Comment by robertsLando** [comment] 2020-05-18 07:37
> I saw the same behaviour using this tool against Aedes running on a Raspberry Pi 3.

@martin-doyle could you take a memory snapshot so we can understand where the memory leak is (if any)?

**Comment by mogupta** [comment] 2020-05-18 08:26
How can I take the snapshot ? Using node inspector ?

**Comment by robertsLando** [comment] 2020-05-19 06:25
Yes @mogupta https://www.toptal.com/nodejs/debugging-memory-leaks-node-js-applications

**Comment by mogupta** [comment] 2020-05-19 09:13
Thanks. I will get it to you as soon as possible

**Comment by weiliudong** [comment] 2020-05-19 10:18
I started the broker directly using memory, and reached a certain amount of connections, but also appeared that I could not publish or subscribe, but only connect.

**Comment by robertsLando** [comment] 2020-05-19 11:44
@weiliudong Could anyone point out what causes this? I think the problem could be a memory leak but in order to know this we need a memory snapshot, I'm not able to replicate this even using mqtt-stresser

**Comment by mogupta** [comment] 2020-05-20 04:18
So the problem occurred agan when I added back the auth hook. So I think the problem is not a memory leak. What are your thoughts? The server is still on a Higher CPU/ Memory configuration. I even saw the Memory/ CPU usage. I did check CPU / RAM when the aedes started acting up. There were plenty of resources available.

**Comment by robertsLando** [comment] 2020-05-20 06:14
So the problem seems to happen only when the auth hook is present?

@martin-doyle @weiliudong Are you using auth hooks too?

Could you all provide your aedes setup?

**Comment by mogupta** [comment] 2020-05-20 06:14
Yes

**Comment by robertsLando** [comment] 2020-05-20 06:15
@mogupta Could you paste here your auth hook? (did you make it without using async function?)

**Comment by mogupta** [comment] 2020-05-20 06:18
The auth hook is available in the topmost comment (pastbin). I have only
removed the "async" from the function. I was not using await earlier so no
other changes were made.

**Comment by robertsLando** [comment] 2020-05-20 06:33
Just noticed that the promise doesn't have a catch block, if the promise fails the auth never returns a value to the callback

**Comment by mogupta** [comment] 2020-05-20 06:41
If their is an err from either of the two mongodb requests it will resolve(false). This will eventually call the callback. I will add the catch block to be sure.

**Comment by robertsLando** [comment] 2020-05-20 14:40
@mogupta After speaking with @mcollina he has suggested a fix and I have created a PR for that. COuld you kindly test that?

**Comment by martin-doyle** [comment] 2020-05-20 19:08
I do not use the auth hook, just a plain server like this:
```
const aedes = require('aedes')();
const server = require('net').createServer(aedes.handle);
const port = 1883;



server.listen(port, function () {
  console.log('server started and listening on port ', port);
});
```
If I run mqtt-stresser with 100 clients and 100 up to 1000 messages - no problem no matter how often I repeat the test. 
With more clients and/or more messages I see 3 symptoms:

1. Aedes crashes with 

```
D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:89
  this.release = function (err, result) {
                          ^

RangeError: Maximum call stack size exceeded
    at PublishState.ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:89:27)
    at ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:99:22)
    at Aedes.defaultPublished [as published] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\aedes.js:332:3)
    at PublishState.callPublished (D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\aedes.js:219:15)
    at makeCall (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:113:10)
    at MQEmitter.ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:96:9)
    at MQEmitter.parallel [as _parallel] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastparallel\parallel.js:25:12)
    at MQEmitter._do (D:\Martin\Dokumente\workspace\aedes-test\node_modules\mqemitter\mqemitter.js:127:8)
    at released (D:\Martin\Dokumente\workspace\aedes-test\node_modules\mqemitter\mqemitter.js:61:12)
    at MQEmitter.parallel [as _parallel] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastparallel\parallel.js:26:7)
```
or
```
D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\lib\client.js:53
  function nextBatch (err) {
                     ^

RangeError: Maximum call stack size exceeded
    at Client.nextBatch [as _nextBatch] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\lib\client.js:53:22)
    at PublishState.ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:99:22)
    at ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:99:22)
    at Aedes.defaultPublished [as published] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\aedes.js:332:3)
    at PublishState.callPublished (D:\Martin\Dokumente\workspace\aedes-test\node_modules\aedes\aedes.js:219:15)
    at makeCall (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:113:10)
    at MQEmitter.ResultsHolder.release (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastseries\series.js:96:9)
    at MQEmitter.parallel [as _parallel] (D:\Martin\Dokumente\workspace\aedes-test\node_modules\fastparallel\parallel.js:25:12)
    at MQEmitter._do (D:\Martin\Dokumente\workspace\aedes-test\node_modules\mqemitter\mqemitter.js:127:8)
    at released (D:\Martin\Dokumente\workspace\aedes-test\node_modules\mqemitter\mqemitter.js:61:12)
```

2. I lose messages
```
100 worker started
........................Test timeout. Wait 5s to allow disconnection of clients.

# Configuration
Concurrent Clients: 100
Messages / Client:  1000000

# Results
Published Messages: 1000000 (100%)
Received Messages:  838752 (84%)
Completed:          24 (24%)
Errors:             0 (0%)
```
3. Aedes memory increases to high levels like 750MB 

I made several Heap snapshots. Where do you want me to send it to?

**Comment by mogupta** [comment] 2020-05-21 08:17
@robertsLando I made some changes myself. I will let you know how it goes. It's been 24 hour since I didn't had any issue.

**Comment by mogupta** [comment] 2020-05-23 03:14
```
var authenticate = function(client, username, password, callback) {
    let errorAuth = new Error()
    errorAuth.returnCode = 4;

    console.log("authorize :-", username);
    if (!username) {
        console.log("No username provided");
        return callback(errorAuth);
    }
    let userSplit = username.split("-");
    if (userSplit.length != 2) {
        console.log("userSplit less than len 2");
        return callback(errorAuth);
    }

    var userType = userSplit[0],
        username = userSplit[1];

    if (bannedDeviceIds[username]) {
        console.log("Banned User ", username);
        return callback(errorAuth);
    }
    
    new Promise((resolve) => {
        if (userType == 'user') {
            User.findById(username, (err, user) => {
                if (err) return resolve(false);
                resolve(password.toString() === _.get(user, 'mqttPassword'));
            });    
        } else if (userType == 'device') {
            Device.findById(username, (err, device) => {
                if (!device) bannedDeviceIds[username] = true;
                if (err || !device) return resolve(false); 
                let result = device.enabled == true && 
                            password.toString() === _.get(device, 'mqttPassword');
                if (!result) { 
                    bannedDeviceIds[username] = true
                    console.error("not authorized, device id = ", device.id);
                }
                resolve(result);                        
            });    
        }
    }).then((authorized) => {
        console.log(authorized, " - ",username)
        if (authorized) {
            client.user = username;
            client.userType = userType;
            callback(null, authorized);
        } else {
            callback(errorAuth, null);
        }    
    }).catch((err) => {
        console.log("Error occurred while authorizing ", err, " ", userType, " ", username)
    })        
}
```

**Comment by mogupta** [comment] 2020-05-23 03:16
This is what have worked so far (72 hours). I looked up the logs and found that the catch has never trigger. So banning deviceIds which were deleted made it stable. mosca handled it without a sweat.

**Comment by mogupta** [comment] 2020-05-25 09:39
Same problem happened last night. @robertsLando should I try out your PR ?

**Comment by robertsLando** [comment] 2020-05-25 09:40
@mogupta Yes please. Try that pr

**Comment by robertsLando** [comment] 2020-05-25 09:42
@martin-doyle Based on the logs you shared I think you are running an old version od Aedes. COuld you try with latest version please?

**Comment by martin-doyle** [comment] 2020-05-25 15:32
Yes, the latest version does NOT stop with `Maximum call stack size exceeded`. But Aedes still stops on heavy (mqtt-stresser) load.

For me this is not an issue since I do not have such heavy load on my installation. mqtt-stesser was just a hint in order to reproduce the described behaviour.

**Comment by robertsLando** [comment] 2020-05-25 15:35
> I made several Heap snapshots. Where do you want me to send it to?  

Dropbox link?

**Comment by martin-doyle** [comment] 2020-05-25 16:11
https://www.dropbox.com/sh/75gxfpncqecaqak/AAAuFwHMyNGvcMorhXBi66wTa?dl=0

**Comment by mogupta** [comment] 2020-05-26 03:15
@robertsLando deplyed to prod.

**Comment by robertsLando** [comment] 2020-05-26 06:39
@martin-doyle Thanks

**Comment by mogupta** [comment] 2020-06-03 12:57
@robertsLando so it was working fine till today. I added back the authorizeSubscribe and authorizePublish and the same problem came back just after a few hours after the update. Any suggestions , I used your branch.

**Comment by robertsLando** [comment] 2020-06-03 13:13
But at least with that fix things was working better? I mean before adding authorize functions?

**Comment by mogupta** [comment] 2020-06-03 13:15
Yes , everything worked fine. Please note that for the past 8 days the authenticate function was there but not the Authorize functions.

**Comment by robertsLando** [comment] 2020-06-03 13:19
So the fix has partially fixed something, we need to understand why and how authorize functions can create problems

**Comment by robertsLando** [comment] 2020-06-04 07:37
@mogupta Could you please paste here your authorize functions? Did you remove async from them?

**Comment by mogupta** [comment] 2020-06-04 07:40
@robertsLando the pastbin link at the top has everything you need. Yes I did remove async .

**Comment by mogupta** [comment] 2020-06-04 07:41
> ```
> var authenticate = function(client, username, password, callback) {
>     let errorAuth = new Error()
>     errorAuth.returnCode = 4;
> 
>     console.log("authorize :-", username);
>     if (!username) {
>         console.log("No username provided");
>         return callback(errorAuth);
>     }
>     let userSplit = username.split("-");
>     if (userSplit.length != 2) {
>         console.log("userSplit less than len 2");
>         return callback(errorAuth);
>     }
> 
>     var userType = userSplit[0],
>         username = userSplit[1];
> 
>     if (bannedDeviceIds[username]) {
>         console.log("Banned User ", username);
>         return callback(errorAuth);
>     }
>     
>     new Promise((resolve) => {
>         if (userType == 'user') {
>             User.findById(username, (err, user) => {
>                 if (err) return resolve(false);
>                 resolve(password.toString() === _.get(user, 'mqttPassword'));
>             });    
>         } else if (userType == 'device') {
>             Device.findById(username, (err, device) => {
>                 if (!device) bannedDeviceIds[username] = true;
>                 if (err || !device) return resolve(false); 
>                 let result = device.enabled == true && 
>                             password.toString() === _.get(device, 'mqttPassword');
>                 if (!result) { 
>                     bannedDeviceIds[username] = true
>                     console.error("not authorized, device id = ", device.id);
>                 }
>                 resolve(result);                        
>             });    
>         }
>     }).then((authorized) => {
>         console.log(authorized, " - ",username)
>         if (authorized) {
>             client.user = username;
>             client.userType = userType;
>             callback(null, authorized);
>         } else {
>             callback(errorAuth, null);
>         }    
>     }).catch((err) => {
>         console.log("Error occurred while authorizing ", err, " ", userType, " ", username)
>     })        
> }
> ```
Here it is

**Comment by robertsLando** [comment] 2020-06-04 07:43
@mogupta Yes I checked it but it still has async functions and I would like to check how you fixed it, also you have pasted the authenticate function here and based on what [you said](https://github.com/moscajs/aedes/issues/483#issuecomment-638189519) it was working good with that.

**Comment by mogupta** [comment] 2020-06-04 08:15
https://pastebin.com/xDY7Sn6H
Here is the complete code. I just noticed I didn't remove the async functions from validateRequest function which is part of the authorizeSubscribe  and authorizPublish

**Comment by robertsLando** [comment] 2020-06-04 08:19
Try with: 

```js
// In this case the client authorized as alice can publish to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizePublish = function(client, packet, callback) {
    validateRequest(client, packet).then(err => {
    callback(err)
     if (!err)   deviceToggled(client, packet.topic, packet.payload);
 }).catch(// catch the error) 
}
 
// In this case the client authorized as alice can subscribe to /users/alice taking
// the username from the topic and verifing it is the same of the authorized user
var authorizeSubscribe = async function(client, sub, callback) {
   validateRequest(client, packet).then(err => {
    callback(err, sub)
     if (!err)   deviceToggled(client, packet.topic, packet.payload);
 }).catch(// catch the error) 
}
```

**Comment by mogupta** [comment] 2020-06-06 04:12
@robertsLando same problem reappeared. Not sure what to do. Here is my updated code
https://pastebin.com/0UfFUwnv
I am using 0.42.1 of aedes which has the fix.

**Comment by robertsLando** [comment] 2020-06-08 07:19
The strange thing here is that if you run the code without your autorize functions there is no problem, so I don't know how and why but seems those functions are creating problem and it's not really something related to aedes itself. I say this because authorize functions (authorizePublish and authorizeSubscribe) are used even when not defined by the user so it couldn't be a memory leak with callbacks. At this point I have no more solution for you, I'm sorry

**Comment by bhirave** [comment] 2020-06-11 12:51
Hello All,
did you guys resolved this issue ? i am in the process of migration of `mosca` to `aedes`. We use Auth hooks heavily. Any particular reason that `async/await` should be changed `promise` based handling in `auth` hooks ?.

**Comment by robertsLando** [comment] 2020-06-11 13:33
> Any particular reason that async/await should be changed promise based handling in auth hooks ?

Because aedes treats them as functions and not promises. When you call `fn(cb)` and `fn` is `async` it will return a promise

**Comment by bhirave** [comment] 2020-06-11 14:08
@robertsLando thanks. Is it same case for `authenticate` hook as well ?

**Comment by robertsLando** [comment] 2020-06-11 14:11
@bhirave Yes

**Comment by bhirave** [comment] 2020-06-11 15:33
@robertsLando but when i use `async/await` on these hooks, seems like its working fine so far. But i havent done any load testing as @mogupta performed. Here is my code snippet- 

`
async function authorizeSubscribe(client, sub, cb) {
    let authorized = false;
    let errorMessage = "";
    try {
        if (someCondition == true) {
            authorized = await callBackEndAPI();
        }
        else {
            authorized = await callSecondApi();
        }
        return;
    }
    catch (error) {
        authorized = false;
        error = "Error occured";
    }
    finally {
        if (!authorized) {
            cb(new Error(errorMessage));
        }
        else {
            cb(null, sub);
        }
    }
}`

**Comment by robertsLando** [comment] 2020-06-11 15:36
I didn't say it would not work, it works but could cause some memory leaks problems, expecially with high loads

**Comment by bhirave** [comment] 2020-06-11 15:43
Thanks @robertsLando . I am really looking forward to hear solution / fix for original thread @mogupta  started. so i could take care of it before we perform migration from **mosca** to **aedes**. Let me run some benchmarking tools, see what happens with it.

**Comment by bhirave** [comment] 2020-06-11 19:19
@mogupta @robertsLando  i also found that, if you dont set `maxClientsIdLength`, default value is 23 (?). So i am running benchmark tool right now, my client was generating random id (and length was more than 23). 

three observations
- if client id length is more than 23, and auth/authz hooks are async/await, with 150 clients, broker stopped responding without any error

- if client id length is more than 23, and NO AUTH HOOKS, with 150 clients, broker stopped responding but throws error - `identifier rejected`

- if client id is specified (lets say 50), and auth/authz hooks are still `async/await`, broker does continuously operate
- if

**Comment by robertsLando** [comment] 2020-06-11 21:03
That’s interesting! I would like to know if @mogupta is using clientsId with 23 or more charaters. There must be a memory leak in connect handler when return code is 2. I will dig into this tomorrow 

---

Daniel

**Comment by bhirave** [comment] 2020-06-12 02:04
@mogupta i would recommend you to add following subscriptions, so you can get more logging, why subscription being stopped

`aedes.on('connectionError', function (client, err) {
    console.log('client connection Error:', clientInfo.id, "==>", err.message);
    // disconnect client
    client.close();
});


aedes.on('clientError', function (client, err) {
    console.log('client error:', clientInfo.id, "==>", err.message);
    // disconnect client
    client.close();
});`

**Comment by mogupta** [comment] 2020-06-12 04:22
Hi @bhirave 
Example
Device Client's id is **IOTSSClient-b5e4** 16 char
User Client id (APP) **5d7115f6d7ec8c00c5454e34** 24 char
Username - **user-5d7115f6d7ec8c00c5454e34**  29 Char
password - **98d7ff8e-ac63-11ea-bb37-0242ac130002** 36 Char

 I noticed that when the problem happens, on publishing requests from APP and MQTT no error occurers . The client  stays connected but is unable to receive publish messages which it has subscribed to.

**Comment by bhirave** [comment] 2020-06-12 04:25
@mogupta whats max number of connections will be connected at that point when error occures ?

**Comment by mogupta** [comment] 2020-06-12 04:26
@bhirave ~400

**Comment by bhirave** [comment] 2020-06-12 04:28
and messages published / subscribed - what is QoS ? just out of curiosity - did you MongoDB status - which is your message persistance ? We had mongo+mosca, but we are moving away from that to aedes+redis.

**Comment by mogupta** [comment] 2020-06-12 04:30
@bhirave QOS 0 . Persistence is mongo+aedes

**Comment by bhirave** [comment] 2020-06-12 04:38
@mogupta might be adding those events (https://github.com/moscajs/aedes/issues/483#issuecomment-643023613), can help you to monitor situation.

**Comment by bhirave** [comment] 2020-06-12 04:40
@mogupta what are you using for monitoring - https://github.com/moscajs/aedes/issues/483#issuecomment-639976851 indicates that broker is flooded and it cant accept new connections any more ?

**Comment by mogupta** [comment] 2020-06-12 04:49
@bhirave I will try those tomorrow morning IST (when my users are sleeping) . The broker doesn't seem to be flooded. No matter how I try and how many connections are alive, the broker stops accepting publish messages. no error is returned on the client. I tried with Mqttfx when the broker was misbehaving.

**Comment by mogupta** [comment] 2020-06-12 04:50
@bhirave for the monitor I am just publishing a random number every 60 seconds and expecting the same message back using mqttjs. If it fails for 5 consecutive times , docker restarts the container.

**Comment by robertsLando** [comment] 2020-06-12 08:30
Just found this bug, @mogupta @bhirave could you please give a try to `fix#connect` branch ?

**Comment by mogupta** [comment] 2020-06-12 13:28
@bhirave can you please load test again to see if the issue is resolved. I can't push testing code to production often.

**Comment by mogupta** [comment] 2020-06-13 00:13
@robertsLando @bhirave Deployed to production with the fix and also the [Comment](https://github.com/moscajs/aedes/issues/483#issuecomment-643023613)

**Comment by robertsLando** [comment] 2020-06-15 07:11
@mogupta Is it working now?

**Comment by mogupta** [comment] 2020-06-15 07:12
@robertsLando I would need at least a week to confirm if the problem is resolved. It happens spordiacly

**Comment by mogupta** [comment] 2020-06-18 00:30
@robertsLando everything is fine till now . I just noticed the following message today.

`(node:17) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added to [MongoPersistence]. Use emitter.setMaxListeners() to increase limit`

**Comment by robertsLando** [comment] 2020-06-18 06:27
@mogupta I suggest you to pass to aedes the db connection instead of the url and wait for persistence ready to start the server, that could happen when aedes receives lot messages and the persistence is not ready

**Comment by mogupta** [comment] 2020-06-18 23:55
@robertsLando the server stopped publishing twice yesterday. I think the logs are not more elaborate. Thanks to @bhirave . See below. So right after the following messages , aedes stopped publishing new message. If you want the entire logs I can email you . thanks

```
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093209172Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093482716Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093552058Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093699472Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093810793Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.093955627Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094068204Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094253364Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094473168Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094590768Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094747768Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.094851425Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.09495139Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095058587Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095196693Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095329509Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095486774Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.09564846Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095740904Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.095871309Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096018263Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096180092Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096282645Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096421868Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096607037Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096714613Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096844501Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.096970686Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097104381Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097282931Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097398139Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097543082Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097665983Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097815047Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.097921142Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098077904Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098189686Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098355294Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098599041Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098747251Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.098867812Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.099027918Z"}
{"log":"client error: 5d03f9a75f30da00c50022da ==\u003e connection closed\n","stream":"stdout","time":"2020-06-18T19:01:12.099159166Z"}

```

**Comment by mogupta** [comment] 2020-06-18 23:57
> @mogupta I suggest you to pass to aedes the db connection instead of the url and wait for persistence ready before starting the server, that could happen when aedes receives lot messages and the persistence is not ready or/and you could use `mongoPersistence.setMaxListeners` to increese max listeners

I have made the following changes and deployed. The mongoPersistence object doesn't seem to return anything. So not sure how do I make sure that mongoPersistence has instantitated properly before Aedes starts up ? 
```
let mongoAedesPersistence = mongoPersistence({
    url: process.env.MONGO_MQTT_URL,
    ttl: {
        packets: {
          incoming: 100,
          outgoing: 100,
          will: 300,
          retained: -1
        }, // Number of seconds
      //   subscriptions: 1,
      },
      dropExistingIndexes: true
});

var settings = { 
    mq: emitter,
    persistence: mongoAedesPersistence,
    concurrency: 1000
};
```

**Comment by bhirave** [comment] 2020-06-19 01:56
@mogupta Thanks. Not sure this help. But i usually disconnect / close client on `client error`

```
    broker.on('clientError', function (client, err) {
        let clientInfo = utils.getClientInfo(client);

        console.log('client error:', clientInfo.userName, "==>", err.message);

        if (telementry) telementry.trackEvent({ name: "clientError", properties: { clientId: clientInfo.clientId, user: clientInfo.userName, clientType: clientInfo.clientType, userEmail: clientInfo.userEmail, errorMessage: err.message } });

        // disconnect client
        client.close();
    });
```

**Comment by robertsLando** [comment] 2020-06-19 06:11
Ok I have checked your code again @mogupta, seems you are using mqemitter-mongodb, if you are not using aedes with clusters there is no reason to use that emitter, also in my tests mqemitter-mongodb seems to have some serious memory leak on high loads. I suggest you to use the default emitter `mqemitter` or `mqemitter-redis`. That kind of error could be caused by some memory leaks with that emitter

**Comment by robertsLando** [comment] 2020-06-19 06:15
> Thanks. Not sure this help. But i usually disconnect / close client on client error

It's useless to call `client.close` on clientError as it's already called immediatly after that event is emitted: 
https://github.com/moscajs/aedes/blob/master/lib/client.js#L192

**Comment by mogupta** [comment] 2020-06-19 08:05
@robertsLando I moved to `mqemitter` a while back.

**Comment by robertsLando** [comment] 2020-06-19 08:56
try to set an higher concurrency on mqemitter

**Comment by robertsLando** [comment] 2020-06-19 08:57
About mongodb persistence, you should wait for 'ready` event before starting the server. Check https://github.com/moscajs/aedes-cli/blob/master/lib/cli.js#L325

**Comment by robertsLando** [comment] 2020-06-19 12:37
@mogupta Also are you using wos 0 1 or 2 for your messages? I have found some bugs with qos 2 messages

**Comment by mogupta** [comment] 2020-06-19 12:38
QOS 0

**Comment by robertsLando** [comment] 2020-06-19 13:24
@mogupta Could you try to use this https://github.com/moscajs/aedes/pull/508

**Comment by robertsLando** [comment] 2020-06-23 07:34
@mogupta @bhirave any news?

**Comment by mogupta** [comment] 2020-06-23 07:35
Need a week more. No good or bad news yet. 😀

**Closed** 2020-06-29 08:22 UTC
Labels: bug, help wanted

**Comment by robertsLando** [comment] 2020-07-01 09:44
@mogupta Is this finally fixed so?

**Comment by mogupta** [comment] 2020-07-05 23:47
@robertsLando yeah , problem resolved. I will keep you posted if the problem reappears.
