### ISSUE TITLE
benchmarking - QoS 1/2 db streaming becomes burden when many packets are sent

### ISSUE THREAD

**Issue by syberkitten** [moscajs/aedes#159] opened 2017-10-06 13:38 UTC
I've been testing Aedes using the [malaria benchmark](https://github.com/remakeelectric/mqtt-malaria),
and have some interesting results, that reflect
an interesting behavour.

the test entails sending 1k-10k messages from each process (starting with one)
and subscriber that expects these messages and measures the timing.

any QOS 1 or 2 publication / subscription makes the mongoDB
go crazy and loose performance to quick non responsiveness of
both the node and mongo processes.

the db log is shooting with these:

`

2017-10-06T16:26:24.898+0300 I COMMAND  [conn1] command aedes-persistence.outgoing command: find { find: "outgoing", filter: { clientId: "beem.listr-9015", packet.messageId: 29497 }, limit: 1, singleBatch: true, batchSize: 1 } planSummary: COLLSCAN keysExamined:0 docsExamined:300750 cursorExhausted:1 numYields:2358 nreturned:0 reslen:114 locks:{ Global: { acquireCount: { r: 4718 } }, Database: { acquireCount: { r: 2359 } }, Collection: { acquireCount: { r: 2359 } } } protocol:op_query 304ms
2017-10-06T16:26:25.014+0300 I COMMAND  [conn6] command aedes-persistence.outgoing command: find { find: "outgoing", filter: { clientId: "beem.listr-9015", packet.messageId: 29506 }, limit: 1, singleBatch: true, batchSize: 1 } planSummary: COLLSCAN keysExamined:0 docsExamined:300750 cursorExhausted:1 numYields:2354 nreturned:0 reslen:114 locks:{ Global: { acquireCount: { r: 4710 } }, Database: { acquireCount: { r: 2355 } }, Collection: { acquireCount: { r: 2355 } } } protocol:op_query 272ms
2017-10-06T16:26:25.029+0300 I COMMAND  [conn5] command aedes-persistence.outgoing command: find { find: "outgoing", filter: { clientId: "beem.listr-9015", packet.messageId: 29500 }, limit: 1, singleBatch: true, batchSize: 1 } planSummary: COLLSCAN keysExamined:0 docsExamined:300750 cursorExhausted:1 numYields:2356 nreturned:0 reslen:114 locks:{ Global: { acquireCount: { r: 4714 } }, Database: { acquireCount: { r: 2357 } }, Collection: { acquireCount: { r: 2357 } } } protocol:op_query 271ms
`

Because every test injects many packets that are saved in the outgoing
collection (around 400,000) which also don't seem to be deleted,
so every lookup becomes more expensive than the one before.

we could have billions of outgoing packets that are not yet consumed,
and performance should not drop so drastically with a few thousand.

**Comment by syberkitten** [comment] 2017-10-06 13:42
These are the Malaria commands that makes both mongodb and nodejs
go into a slowhold ... 

until it's like a slow motion repeat that never ends,
make sure to subscribe first and then using a different
terminal screen publish.

if you wish it to actually not fail, just reduce the qos to 1 or 0,
you will feel the enormous difference, including the output
of the mongodb log, which corelate.

Publish:
`
malaria subscribe -n 1000 -N 2 --host localhost -q 2
`

Subscribe
`
malaria publish -t -n 1000 -P 2   --host localhost -q 2
`

**Comment by mcollina** [comment] 2017-10-06 14:29
If you would like to send PRs to the various Mongo modules, it would be fantastic! 

Unfortunately I won’t have availability to work on this for some time, but I can review PRs.

**Comment by syberkitten** [comment] 2017-10-07 10:11
@mcollina 
Gladly! when i figure some things out first :)

When I publish 2000 message using the malaria testing (1000 messages for process)
**Qos 2 publish**
**malaria subscribe -n 1000 -N 2 --host localhost -q 2**
**malaria publish -t -n 1000 -P 2  --host localhost -q 2**

The 'outgoing' collection is left with: 48k documents (packets).
**The same test using QoS 1 publish ** - leaves: 52-54k packets in the 'outgoing' collection.
Using Qos 0 for publish, leaves the 'outgoing' - empty.

should not each message correlate to a packet?
why so many are being created?

**Comment by mcollina** [comment] 2017-10-07 16:12
Would you like to send a PR to address those issues?

**Comment by muka** [comment] 2017-11-09 11:20
I think this is related, at least in its setup. After a few days of usage we get out of memory error. (Do not know yet if it is related to mongodb driver only but surely RAM has gone)

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
broker_1      | 
broker_1      | <--- Last few GCs --->
broker_1      | 
broker_1      | [1:0x2fe9fe0] 472925137 ms: Mark-sweep 1402.9 (1517.0) -> 1402.9 (1517.0) MB, 1591.1 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1591 ms) last resort GC in old space requested
broker_1      | [1:0x2fe9fe0] 472926748 ms: Mark-sweep 1402.9 (1517.0) -> 1402.9 (1517.0) MB, 1610.3 / 0.0 ms  last resort GC in old space requested
broker_1      | 
broker_1      | 
broker_1      | <--- JS stacktrace --->
broker_1      | 
broker_1      | ==== JS stack trace =========================================
broker_1      | 
broker_1      | Security context: 0x359364c25e91 <JSObject>
broker_1      |     1: handleCallback(aka handleCallback) [/app/node_modules/mongodb/lib/utils.js:~116] [pc=0x13e50b29c69d](this=0x34c0dec02311 <undefined>,callback=0x33488241be41 <JSFunction (sfi = 0x2cba4fce60a9)>,err=0x34c0dec02201 <null>,value1=0x156759402339 <BulkWriteResult map = 0x3105e4ad09b9>,value2=0x34c0dec02311 <undefined>)
broker_1      |     2: arguments adaptor frame: 3->4
broker_1      |     4: executeCommands(aka executeComma...
broker_1      | 
broker_1      |  1: node::Abort() [node]
broker_1      |  2: 0x121809c [node]
broker_1      |  3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
broker_1      |  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
broker_1      |  5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [node]
broker_1      |  6: v8::internal::DeoptimizationInputData::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [node]
broker_1      |  7: v8::internal::compiler::CodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [node]
broker_1      |  8: v8::internal::compiler::CodeGenerator::FinalizeCode() [node]
broker_1      |  9: v8::internal::compiler::PipelineImpl::FinalizeCode() [node]
broker_1      | 10: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [node]
broker_1      | 11: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [node]
broker_1      | 12: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [node]
broker_1      | 13: v8::internal::StackGuard::HandleInterrupts() [node]
broker_1      | 14: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [node]
broker_1      | 15: 0x13e50700463d
```

**Comment by syberkitten** [comment] 2017-11-09 11:45
@muka 
My tests revealed that mongo cannot be used with Aedes in production.
I was able to crash the whole system after 5 minutes of testing
as I've described. more so, the mongo store does not clean itself up,
and creates a lot of documents that are looked through each publish, making it slower and slower until crash.

The Redis persistence, except being faster and more suitable for storing keys and topics
which are more light weight then documents, also has the TTL features
which is exactly what is needed to expire old packets which will clog the system.

**Comment by muka** [comment] 2017-11-09 13:09
@syberkitten thank you, I will switch to redis to try out, thank you for the feedback. 

This issue is making the whole mongodb emitter useless, do you have a point in the codebase where to look for a PR ?

**Comment by tripflex** [comment] 2017-12-17 18:47
Forgive me if i'm off-base in this response, but maybe the mongo handling should be using capped collections like it does in ascoltatori https://github.com/mcollina/ascoltatori ?

https://docs.mongodb.com/manual/core/capped-collections/

Glad I came across this issue as my current Mosca setup uses MongoDB handling, and was looking at converting to use Aedes, but now it looks if I do plan that, I may need to look at using Redis instead of MongoDB

**Comment by mcollina** [comment] 2017-12-18 08:18
@tripflex https://github.com/mcollina/mqemitter-mongodb is already using capped collections

**Comment by GavinDmello** [comment] 2018-01-15 23:58
@syberkitten  I can't reproduce this issue in normal operation. The outgoing collection clears itself. I shall test this with malaria once, maybe it's something to do with the way malaria works.

**Comment by robertsLando** [comment] 2020-01-23 12:56
I think that this was related to aedes-persistence-mongo and could be fixed in latest releases

**Closed by robertsLando** 2020-01-23 12:56 UTC
